# Generated by Django 5.2.1 on 2025-12-10 18:57

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_category_order_alter_commande_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('name_fr', models.CharField(max_length=100)),
                ('prix', models.FloatField()),
                ('is_big_steak', models.BooleanField(default=False)),
                ('type_class', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Vendor',
        ),
    ]
