# Generated by Django 5.2.1 on 2025-12-18 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_itemvendor_rename_category_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemvendor',
            name='is_big_steak',
        ),
        migrations.RemoveField(
            model_name='itemvendor',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='itemvendor',
            name='order',
        ),
        migrations.RemoveField(
            model_name='itemvendor',
            name='type_class',
        ),
        migrations.AddField(
            model_name='itemvendor',
            name='nom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itemvendor',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_items', to='api.vendor'),
        ),
    ]
