# Generated by Django 5.2.1 on 2025-12-25 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_itemvendor_is_big_steak_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcommande',
            old_name='category',
            new_name='vendor',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='avec_6begat',
        ),
        migrations.RemoveField(
            model_name='itemcommande',
            name='chicken_number',
        ),
        migrations.RemoveField(
            model_name='itemcommande',
            name='remplissage',
        ),
        migrations.RemoveField(
            model_name='itemcommande',
            name='selected_price',
        ),
        migrations.RemoveField(
            model_name='itemcommande',
            name='with_chicken',
        ),
        migrations.AddField(
            model_name='itemcommande',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='api.itemvendor'),
        ),
    ]
