# Generated by Django 5.2.1 on 2025-12-29 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_category_itemcommande_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='livreur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livreur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemcommande',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.itemvendor'),
        ),
    ]
