# Generated by Django 5.2.1 on 2025-12-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_commande_livreur_alter_itemcommande_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='name_fr',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='title',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='is_big_steak',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='livraison',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='order',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='price1',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='price2',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='price3',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='type_class',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('pharmacie', 'Pharmacie'), ('epicerie', 'Epicerie')], max_length=50),
        ),
    ]
